### ISSUE TITLE
Frostiful causes resourcepack loading to fail at game launch, 1.21 with Fog installed

### ISSUE THREAD

**Issue by MylesGit** [TheDeathlyCow/frostiful#100]
**Describe the bug**
Frostiful bug prevents resourcepacks from loading at launch.

**To Reproduce**
1. Install Frostiful for MC 1.21
2. Launch Game
3. "Failed to load resourcepacks"

**Expected behavior**
I expect resource packs to load like normal.

**Game information**
- MC Version: 1.21
- Loader: Fabric 0.16.0

**Logs**
https://mclo.gs/C9OErrM

**Additional context**
Issue happens on Frostiful Alpha and Beta versions.

**Comment by TheDeathlyCow** [comment]
I;ve had someone also report this on my Discord, but I was unable to replicate it with a more minimal set of mods on fabric loader 0.16.0. I think it might be due to a mod conflict but I'm not sure at this time.

**Comment by MylesGit** [comment]
Found the issue, its a [fog mod](https://mclo.gs/D5NlSMp). With it removed everything loads up correctly. I would try to find whoever reported that prior issue and see if they also had this mod.

**Comment by TheDeathlyCow** [comment]
Yep, can confirm that Fog is causing this issue. Thanks for finding it!

**Comment by TheDeathlyCow** [comment]
Awesome, thanks!
