### ISSUE TITLE
Frostiful Configuration of modded armor for frost resistance via In-game-JSON or straight JSON/TOML

### ISSUE THREAD

**Issue by TheShadyyOneYT** [TheDeathlyCow/frostiful#101]
**Is your feature request related to a problem? Please describe.**

Frostiful is difficult to deal with modded armors when it comes to frost resistance due to the lack of configurations. It's hard to configure each individual armor piece for frost resistance, other than Frostiful and a select few of mods and vanilla already having it.

**Describe the solution you'd like**

My solution is this roughly: https://imgur.com/a/0VtCEoe | A list of the armor you make, and sliders that consist of frost resistance ranging from 0-10 (0 won't display the frost resistance in item lore/description). This will allow people that are stupid like me to understand how to Configurate each individual armor ourselves without needing a 100+ mod combability individually. Here is the link to the mod as I demonstrated in the imgur link: https://www.curseforge.com/minecraft/mc-mods/colytra

**Describe alternatives you've considered**

Another way this could be achieved is via TOML files or JSON file configurations with a basic layout to do this in a similar manner, but not with the ingame config.

**Additional context**

I request this because as I'm a modpack creator and this feature would substantially speed up the process in configurating the frost resistance of each armor indivdually without the need for asking for 100+ mods with armor compatibility.

**Comment by TheShadyyOneYT** [comment]
If something similar can be done with Scorchful as well. that would be lovely.

**Comment by TheDeathlyCow** [comment]
Hi, if you're using 1.20.1-4, you can achieve this with the data driven item attribute modifiers API in Thermoo: https://github.com/thedeathlycow/thermoo/wiki/Item-Attribute-Modifiers

If you're using 1.20.5+, use the appropriate Armor Material tags instead: https://github.com/thedeathlycow/thermoo/wiki/Armor-Materials-API.
