### ISSUE TITLE
Add Herbal Brews to Warmth Food Tag

### ISSUE THREAD

**Issue by Zouzs** [TheDeathlyCow/frostiful#102]
### Revised issue 

Add the [Herbal Brews](https://modrinth.com/mod/lets-do-herbalbrews) teas to the warm foods tag, as optional entries. Scorchful already does this for hydrating items, but it seems I missed this one for Frostiful. Herbal Brews is currently still in 1.20.1, so this should be done after it updates to 1.21.

### Original comment:

I'm not a code savvy, so if this is already a thing, sorry!

I've been trying to set foods from other mods to give the warmth effect, but so far i've had no luck, i love the Herbal Brews mod, and i think it would fit a lot if they gave the warmth effect.

Maybe a config file to add modded food id's so they are tagged as warmth food would be cool, but not idea if it would be too difficult to do.

Frostiful 1.0.9 - 1.20.1 - Quilt

**Comment by Zouzs** [comment]
Oops, found it,

https://github.com/TheDeathlyCow/frostiful/wiki/Config

**Comment by Zouzs** [comment]
Oops, found it.
https://github.com/TheDeathlyCow/frostiful/wiki/Config

**Comment by TheDeathlyCow** [comment]
> I've been trying to set foods from other mods to give the warmth effect, but so far i've had no luck, i love the Herbal Brews mod, and i think it would fit a lot if they gave the warmth effect.

I can add Herbal Brews to the tag when it is updated to 1.21. Will reopen this issue for that. 

> Maybe a config file to add modded food id's so they are tagged as warmth food would be cool, but not idea if it would be too difficult to do.

The tag is the way to do this, it will not be added to the config.

**Comment by TheDeathlyCow** [comment]
> Oops, found it. https://github.com/TheDeathlyCow/frostiful/wiki/Config

Bear in mind that the wiki is written for 1.21, so some things may be different from 1.20.1.

**Comment by Zouzs** [comment]
It did worked! Actually here the datapack with the compatibility as a apologize contribution. (Maybe it could help someone else)

[Herbal Compatibility.zip](https://github.com/user-attachments/files/16643429/Herbal.Compatibility.zip)

**Comment by Zouzs** [comment]
Oops, i reopened the issue by commenting that.

Closed!

**Comment by TheDeathlyCow** [comment]
i reopened the issue lol
