### ISSUE TITLE
[1.20.1] Frostolger can stun lock the player if it targets another mob,

### ISSUE THREAD

**Issue by Reshy** [TheDeathlyCow/frostiful#104]
**Describe the bug**
Frostolger can stun lock the player if it targets another mob, the mob will not aggro or be frozen but the player will and this means the frostolger will keep using it's ice spell over and over and over and if you don't got a bow or something to escape you just dir veeeery slowly.

**To Reproduce**
1.   Befriend wolf
2.   Aggro a Frostolger
3.   Have the wolf attack the frostolger
4.  Stand near the aggro'd wolf for infinite stun lock.

**Expected behavior**
Frostolger should be aggroing the creatures it shoots at and if it freezes the player again it shouldn't refresh the duration (or perhaps have some sort of other effect)

**Game information (please complete)**
- MC Version (1.20, 1.20.1, etc):   1.20.1
- Loader (Fabric/Quilt or NeoForge with Connector):  Connector

**Additional context**
![image](https://github.com/user-attachments/assets/6f9c1f7b-f0e8-4626-8f31-20bf76a32562)
![image](https://github.com/user-attachments/assets/bb437e22-a2d2-47e7-93c2-85f0ec899c3d)
![image](https://github.com/user-attachments/assets/709b2643-ccca-47ec-9e99-dd4aa2fa95c8)

Wolves or other friendly mobs are also able to abuse this to freely kill the frostolger.
![image](https://github.com/user-attachments/assets/d8128ae5-a913-4c84-930b-837c1fafa9db)

**Comment by TheDeathlyCow** [comment]
ive fixed this on main now. i will probably not release until later this week so I can get a couple more things in, but feel free to build and use early if you like.
