### ISSUE TITLE
Icicle Duplication Glitch

### ISSUE THREAD

**Issue by MrBl4ckSkull** [TheDeathlyCow/frostiful#107]
**Describe the bug**
Whenever thrown icicles are picked up off the ground, you get more than 1 icicle. In fact, oddly enough, you get as many icicles you had in your inventory at the time, +1. So if you had 32 icicles, you'll gain 33 icicles when you pick up the thrown icicle (I noticed this seems to cap at 64).
**To Reproduce**
1. Throw Icicle onto the ground
2. Pick up the thrown icicle projectile
3. You will gain icicles equal to the amount you had in your inventory, with 64 being the max.

**Expected behavior**
You pick up 1 icicle off the ground, not any more than that.

**Game information (please complete)**
- MC Version 1.21
- Fabric Loader

**Additional context**
I replicated this with no other mods present except Frostiful (V1.3) and its dependencies.
Here is a quick video I recorded.
https://github.com/user-attachments/assets/bdd50f86-fc32-4a50-866a-1d7e0c5ee014

**Comment by TheDeathlyCow** [comment]
thanks for the bug report!
