### ISSUE TITLE
Requesting authorization to post MOD on Chinese Minecraft Forum KLPBBS.

### ISSUE THREAD

**Issue by JianyueLab** [TheDeathlyCow/frostiful#108]
Hello, TheDeathlyCow. I’m requesting permission for a friend who’s a big fan of this mod and wants to share it with Chinese Minecraft players. Since he can’t contact you, he’s asking you to authorize him to post this mod on KLPBBS, https://klpbbs.com, with his username, jxhdamjr. Here’s his profile link: https://klpbbs.com/space-uid-403966.html. He’ll ensure your name and related links are included in his post. He seeks your permission to post this mod on the Chinese community.

**Comment by TheDeathlyCow** [comment]
Sure, go ahead. I just will not be able to provide support to users from that site, as I won't be the one uploading it and thus I won't know for sure if anything's been modified without doing some rather tedious checks.

**Comment by JianyueLab** [comment]
Thank you for approve the authorization.
