### ISSUE TITLE
Please Add Structure Crafting & Spawn Settings in Config [1.19.2]

### ISSUE THREAD

**Issue by Kyrthraldergine** [TheDeathlyCow/frostiful#110]
Currently no options to disable spawning / generation of / crafting of mod content. 

Personally desire several features of Frostiful for vanilla+ modpack, but not others.

Requesting following Config options:

1. Enable/Disable the structures
2. Enable/Disable mob spawns.
3. Enable/Disable crafting of armour sets

**Comment by TheDeathlyCow** [comment]
1. you can remove structure spawns by resolving the `frostiful:has_structure/*` tags with empty tags in a datapack.
2. You can remove crafting with item obliterator: https://modrinth.com/mod/item-obliterator
3. You can remove entity spawning with You Shall Not Spawn: https://modrinth.com/mod/you-shall-not-spawn
