### ISSUE TITLE
Data-driven Fur Armor

### ISSUE THREAD

**Issue by ryleu** [TheDeathlyCow/frostiful#16]
It should be possible to set the weather protection of each set of armor through a datapack. As a modpack creator, having that ability would make it much easier to integrate multiple mods with your mod. I'd love to be able to have Noel's Santa armor protect people from freezing too.

It would also work well with mods like indrev that add super powerful armor that should probably also protect you from the cold.

**Comment by ryleu** [comment]
I may make this myself, depending on how much time I have free tomorrow.

**Comment by TheDeathlyCow** [comment]
This is something that's come up on Discord, and probably a good idea. Frost Resistance is determined by attributes, which does mean it has some ability to be configured by item modifiers already; but I admit this is not a great solution as it doesn't cover all instances of an item "generically", so customized armours won't show up with Frost Resistance in the Crafting Book/JEI/creative inventory. It might be something better suited as a general feature for my [Datapack Extensions](https://github.com/TheDeathlyCow/tdc-data) mod, but it could be implemented here as well.

**Comment by ryleu** [comment]
It really depends on whether you think it's within the scope of your data packs mod. If it is, and you add it there, I'd gladly install another mod. I'm using global data packs anyways, so why not?

**Comment by ryleu** [comment]
Works great, thanks!
![image](https://user-images.githubusercontent.com/69326171/208691105-b1187a24-e675-4877-a131-6eb0713038e4.png)

**Comment by ryleu** [comment]
@TheDeathlyCow if I don't specify a slot, it seems to throw a GSON parsing error rather than allowing anything... is there a way to specify that the effect can work on any slot?

**Comment by TheDeathlyCow** [comment]
just duplicate it for different slots :)

i would caution that the tooltip for having attribute modifiers apply to all slots would be very large though, since minecraft breaks it down by slot

**Comment by TheDeathlyCow** [comment]
And one more thing I'd like to add- 

It is an intentional design feature that frost resistance never even gets close to 100%. Being able to completely negate frost altogether sort of defeats the purpose of having frost as a mechanic in the first place. If you want to have it at or very near to 100%, it should either be a temporary, nonrenewable thing, or there should be some drawback that makes you not always have 100% resistance at all times.
