### ISSUE TITLE
Icicles grow in weird places

### ISSUE THREAD

**Issue by ryleu** [TheDeathlyCow/frostiful#18]
Icicles seem to grow inside houses, which is very strange. Maybe having them melt in high enough light levels would fix this?

**Comment by TheDeathlyCow** [comment]
This is sort of intentional, sort of not? The way I've thought to resolve this was just simply using slabs/stairs to block possible locations for icicles. However, it would probably be more in line with vanilla if icicles could not form in block light >10 at all.

**Comment by TheDeathlyCow** [comment]
The update I'll be releasing soon will contain the change in that above commit. Not 100% on what the exact light level should be yet, I want it to both be able to block icicles forming inside houses but also not block them forming on the outside overhangs of houses. The light level is configurable though, so play around with it and let me know what you think.

**Comment by ryleu** [comment]
I'll mess with it and let you know. For now, I have just disabled icicle spawning altogether as I have a way to make it work with another mod. Once you release this update, I'll do some experiments and find what works for me.

**Comment by ryleu** [comment]
a light level of 7 could work well, if you don't count sunlight. that way players can have a lit build where creatures don't spawn while still letting icicles spawn by placing redstone torches
