### ISSUE TITLE
Add compatibility with Primal Winter mod? [suggestion]

### ISSUE THREAD

**Issue by macaroni0423** [TheDeathlyCow/frostiful#27]
If you can, can you make a world spawn cold wind in all biomes if the Primary Winter mod is installed?
Alternatively, please add config that allow cold wind can spawn in all biomes.
(Primary Winter is a mod that makes snow fall across the whole world.)

mod link
https://www.curseforge.com/minecraft/mc-mods/primal-winter

I used a translator, and there may be a grammatical error. sorry.

**Comment by TheDeathlyCow** [comment]
Yep, I can do that! Thanks for letting me know about it.

**Comment by TheDeathlyCow** [comment]
Also, I should add that you can add `#minecraft:is_overworld` to the biome tag `#frostiful:freezing_wind_always_spawns` to get Freezing Wind to spawn in all biomes, all the time.

**Comment by TheDeathlyCow** [comment]
Closing as biome tag allows for config to spawn wind in all biomes
