### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by fforepretty** [TheDeathlyCow/frostiful#42]
I have created a Chinese translation for this mod and how to upload it to the author

**Comment by TheDeathlyCow** [comment]
You can submit a pull request with the new file in assets/frostiful/lang or just upload it in a reply to this issue

**Comment by fforepretty** [comment]
[zh_cn.zip](https://github.com/TheDeathlyCow/frostiful/files/12259036/zh_cn.zip)

At present, this is just a simple sinicization, waiting for future improvement

**Comment by fforepretty** [comment]
[zh_cn(update).zip](https://github.com/TheDeathlyCow/frostiful/files/12259293/zh_cn.update.zip)

Sorry, I optimized it again, please use this!

**Comment by TheDeathlyCow** [comment]
Thank you very much for the translation!
