### ISSUE TITLE
Can you add compatibility with pyrofrost

### ISSUE THREAD

**Issue by fforepretty** [TheDeathlyCow/frostiful#45]
Pyrofrost is another module related to temperature, which would be very suitable when paired with frost
https://modrinth.com/mod/pyrofrost
（Since environmentZ does not have version 1.20.1, I used Pyrofrost）
Don't worry, this is just an insignificant request

**Comment by TheDeathlyCow** [comment]
I think it would be easier if Pyrofrost used Thermoo as their temperature backend - since it would mean that it would work with Frostiful out of the box. It is probably possible to add a compat, though that'll probably be a low-priority thing as I have plans to make a heat mod of my own.

**Comment by TheDeathlyCow** [comment]
Sure thing! @TalonFox  

Thermoo is really just a library mod at its core that helps to unify the temperature data piece for multiple temperature based mods. Thermoo does, however, come with an EnvironmentController to help unify potentially common usages of temperature change to entities, such as from the environment, or from powder snow. The values in the default controller are put into a common config, however each aspect of the controller is able to be overriden via the use of a decorator. So, if you want to change how a particular value is calculated or throw it away all together and replace it with something else, you can do so through the decorator. You could even throw away all the default stuff and implement all those changes yourself, but it would all be done using the Thermoo backend and so its temperature would work natively with Frostiful (and soon, Scorchful). 

This page on the mod wiki has more details about it: https://github.com/TheDeathlyCow/thermoo/wiki/Environment-Controller-and-Events-(Mods) 

I'm also very open to any suggestions you may have with Thermoo, and more than willing to add stuff that may be more suitable towards a mod with heat in it. Thermoo was originally just an extraction of the original Frostiful backend into a library mod, and so many of its default values were set and designed with just cold temperatures in mind.

**Comment by TalonFox** [comment]
@TheDeathlyCow

Thermoo looks like a pretty good library to integrate support for
I'll try to add integrate support whenever I get time to work on Pyrofrost
