### ISSUE TITLE
[Fabric 1.20.1] Errors shows up in the log

### ISSUE THREAD

**Issue by kingkuys2123** [TheDeathlyCow/frostiful#46]
`Failed to load palette image` and `unable to apply palette` Worker-ResourceReload-5 Errors shows up in the log.

https://pastebin.com/G3HM8xjM

**Comment by TheDeathlyCow** [comment]
The message comes from a builtin compatibility patch I did for the custom trim materials added by Geode+. If the trim is still otherwise showing fine, then the warning can be safely ignored.
