### ISSUE TITLE
Sitting near a heat source stops the heating effect

### ISSUE THREAD

**Issue by MadByteDE** [TheDeathlyCow/frostiful#47]
Hi, thanks for the awesome mod! :+1: 

I found that sitting near a campfire, lava or a torch will stop the heating / start the freezing effect.

I tried sitting in a boat and using a QoL mod feature provided by the mod "Vanilla Refresh" which adds the ability to sit everywhere.

**Mod Version:** 0.8.1
**Minecraft:** 1.20.1

**Comment by TheDeathlyCow** [comment]
This issue seems to come from Thermoo, probably because my temperature tick is injected into `tickMovement` and not the base `tick` method for living entities. 

Thanks for the report!
