### ISSUE TITLE
Skin layer, armor, equipped shield not rendering 1.20.1

### ISSUE THREAD

**Issue by YkVox** [TheDeathlyCow/frostiful#49]
Using qfapi-7.2.0_qsl-6.1.1_fapi-0.88.0_mc-1.20.1

after a little digging i found the conflicting mods
the mentionned mods are all up to their latest version

frostiful combined with any cape or skin restorer will cause the outer skin layer and other player visual elements and cape to dissapear

![image](https://github.com/cybercat-mods/gigeresque/assets/61479000/ee37b47e-17d8-4a16-8220-7f7107750384)

the tried mods are:
-Kappa
-Capes
-SkinRestorer
-FabricTailor

thank you in advance !

**Comment by TheDeathlyCow** [comment]
Hi, sorry it took a while to get to this. I can't seem to replicate the issue on my end. Are you playing the game on a server, or in offline mode?

**Comment by YkVox** [comment]
no problem !
i believe this happens when playing on an offline server (i am playing online mode)

**Comment by TheDeathlyCow** [comment]
Ah, ok. I did manage to get this replicated using an offline server. From my testing, the current dev branch seems to have fixed this. It was possibly due to a related issue to #50.

**Comment by YkVox** [comment]
amazing ! i'll go test this out, many thanks !

**Comment by TheDeathlyCow** [comment]
Closing due to candidate fix now being merged into main. I can reopen if the issue still persists, however I do believe it is fixed now.
