### ISSUE TITLE
Crash with tooltips F3+H

### ISSUE THREAD

**Issue by Cikodel** [TheDeathlyCow/frostiful#52]
When I use the shortcut F3+H to display the id's of the blocks, items, etc, the game crashes, the crash report indicates that it is a problem with the mod.

https://pastebin.com/PtQfXPN7

**Comment by TheDeathlyCow** [comment]
That log looks like you are using Forge... can you confirm that this is on Fabric?

**Comment by TheDeathlyCow** [comment]
If you're using some sort of Forge version of the Fabric API to get Frostiful to work on that platform, the crash report indicates that for some reason they pass an immutable map to the `ModifyItemAttributeModifiersCallback` event. This is not the documented behaviour for Fabric API and an issue on their end, not mine.
