### ISSUE TITLE
Frozen mobs should not be able to attack

### ISSUE THREAD

**Issue by phosmiro** [TheDeathlyCow/frostiful#60]
Currently, the Frost Wand only freezes mobs' positions, allowing them to continue attacking such as ranged mobs still being able to shoot or melee mobs attacking when you get close. Consider preventing frozen mobs from attacking, except for Creepers which should retain their explosive ability even when frozen.

**Comment by TheDeathlyCow** [comment]
This was actually done intentionally as it's meant to be "root" not a full "stun" that would completely disable the victim, as that seems a bit overpowered (especially when a player is the victim).
