### ISSUE TITLE
Unclear crash on boot [Fabric 1.20.1]

### ISSUE THREAD

**Issue by Dumpling00** [TheDeathlyCow/frostiful#70]
Help please - love the concept, but there seems to be some kind incompatibility at play. Worth mentioning: My minecraft is heavily modded, but I was wondering if you could help me at least make sense of this crash?

Thank you for your time.
[crash-2024-03-24_10.30.47-client.txt](https://github.com/TheDeathlyCow/frostiful/files/14735949/crash-2024-03-24_10.30.47-client.txt)

**Comment by TheDeathlyCow** [comment]
Uh well I don't see Frostiful mentioned in that crash log anywhere? What exactly is the problem?

**Comment by Dumpling00** [comment]
Really not sure but this only happens if I add Frostiful to my modpack. Everything works perfectly otherwise, It just refuses to boot. I can share the session log if that helps.
https://mclo.gs/rmSVghn

At some point it just starts listing issues with REI but I don't even have it installed anymore so I'm stumped.

**Comment by Dumpling00** [comment]
> Really not sure but this only happens if I add Frostiful to my modpack. Everything works perfectly otherwise, It just refuses to boot. I can share the session log if that helps. https://mclo.gs/rmSVghn
> 
> At some point it just starts listing issues with REI but I don't even have it installed anymore so I'm stumped.

And apparently this doesn't even generate a crash report file, actually. I just assumed that was it since it was the most recent one. Apologies for that, but I'm really not sure what's causing this.

**Comment by Dumpling00** [comment]
I can 100% confirm that REI is not installed anymore and this only happens when I add Frostiful. I'm just as stumped :(

**Comment by TheDeathlyCow** [comment]
Well according to the session log you provided: neither Frostiful, nor Thermoo, nor Scorchful are installed; and REI is. maybe check that you've properly removed the mod JARs? REI could also have a lot of dependencies so I think experiencing crashes even after removing it is to be expected.

**Comment by TheDeathlyCow** [comment]
Also it looks like you have your log level set REALLY low - which is why REI is showing up so much. Maybe try setting it back to info and not debug/trace?

**Comment by Dumpling00** [comment]
Okay, sorry to bother again, but I have reason to believe I might have given you the wrong report still, I've tried again just now and here's the one taken from "latest log", the hour and minute matches so it should be this one.

https://mclo.gs/YVMPcnv

Thank you for your time and patience.

**Comment by TheDeathlyCow** [comment]
Ok thanks, that looks correct. Will look into it.

**Comment by TheDeathlyCow** [comment]
So looking into it, I have no idea why it's crashing or what mod is causing it. The mixin there is correct for the vanilla game, and modifying the item or item stack classes in a way that makes it not work seems like someone has done something very naughty. Regardless, I have made what I think might be a fix. However, since I don't know what mod is causing the error, you will have to test it. You can get the latest dev build by downloading a ZIP file containing the jar from the `Actions` at the bottom of this page: https://github.com/TheDeathlyCow/frostiful/actions/runs/8436509303

Do let me know how it goes.

**Comment by TheDeathlyCow** [comment]
Note: when you install the mod from the artifacts, ensure you install the jar that does NOT have the `-sources` suffix in its name. Install ONLY the jar with the name `frostiful-1.0.7-SNAPSHOT.jar`.

**Comment by Dumpling00** [comment]
I seem to be noticing some random wind/snow particle effects appearing around my base here and there. Couldn't get a video, but is this Frostiful's doing? If so, is there any way to disable this effect?

**Comment by TheDeathlyCow** [comment]
Ok good to hear. If you find any more crashes please report them as a separate issue. 

Also the wind particles are the Freezing Wind effect: https://github.com/TheDeathlyCow/frostiful/wiki/Freezing-Wind

See the config page to find how disable them: https://github.com/TheDeathlyCow/frostiful/wiki/Config
