### ISSUE TITLE
Ability to insulate all armor

### ISSUE THREAD

**Issue by glorification12** [TheDeathlyCow/frostiful#97]
**Is your feature request related to a problem? Please describe.**
Not really. It would be nice to be able to insulate ALL armor instead of just chainmail. Endgame, there shouldn't need to be a sacrifice between defense against damage and defense against cold.

**Describe the solution you'd like**
Maybe an template like the chainmail one, but harder to get, that allows any armor to be padded.

**Describe alternatives you've considered**
A type of fur padding that's harder/rarer to get, that can be used to insulate all armors.

**Comment by TheDeathlyCow** [comment]
Netherite already provides insulation (though, not as much as fur-based armours). Sacrificing armour for other benefits is at the heart of many mechanics in Minecraft (For example: Elytra, Gold Armor in the Nether, Leather/Fur Boots in Mountains, Turtle underwater). If you want to adjust things for your own mod pack, you can use the [Thermoo item attribute modifiers API](https://github.com/TheDeathlyCow/thermoo/wiki/Item-Attribute-Modifiers) (in 1.20), or [Armor Material Tags](https://github.com/TheDeathlyCow/thermoo/wiki/Armor-Materials-API) (in 1.21).
