### ISSUE TITLE
Freezing effects apply to all entities affected

### ISSUE THREAD

**Issue by ihymyly** [TheDeathlyCow/frostiful#99]
Currently, only players are really affected by freezing. Other entities only take 2-3 ticks from freezing before being relieved of the ticking damage, as well as not being able to be affected with the secondary statuses. My proposal is for there to be an option in the config file to enable this for all entities. The idea of this is so that players can benefit more from the features of this mod, being able to use it more strongly in a PvE scenario.

I've attempted to use the "data pack configs", but I'm not sure how to add all entities (even ones from other mods) without making it really, really long.

**Comment by TheDeathlyCow** [comment]
Overriding the base temperature effects in a datapack is the correct way to do it. Simply remove the `entity_type` field from the effect to make them apply to all entities (like is done in the damage effects). You can also use a predicate in the `entity` field to narrow it down a bit based on entity type tag or other conditions, too, if you wish. The only caveat is that expanding effects to tick for all living entities will probably be a bit of a CPU hog. 

This wiki page has the information for the format of temperature effects: https://github.com/TheDeathlyCow/thermoo/wiki/Temperature-Effects-(Mods-and-Datapacks)
